export const skills: Record<string, string[]> = {
  frontend: [
    "HTML",
    "CSS/SCSS",
    "threejs",
    "TailwindCSS",
    "Redux",
    "React/Query",
    "Bootstrap",
    "Javascript",
    "TypeScript",
    "React",
    "Next.js",
    "Framer Motion",
    "GSAP",
    "Redux",
    "RTK",
    "and more...",
  ],
  backend: [
    "Node.js",
    "Express.js",
    "PostgresSql",
    "Mongoose",
    "Prisma",
    "Containers",
    "Socket.IO",
    "PM2",
    "and more...",
  ],
  DESIGNING: [
    "Figma",
    "illustrator",
    "rive",
    "Aftereffects",
    "Blender",
    "and more...",
  ],
  others: ["Git", "Jest", "Cypress","Storybook", "and more..."],
};
