import { clamp } from "../core/NumericGuards";
import type { RibPoint } from "../character/CreatureRig";
import type { AppearanceTuningOverrides } from "../types";
import type { AppearancePalette } from "./AppearancePresets";
import type { GeneratedDecalAtlas } from "./GeneratedDecalAtlas";
import { resolveLocalPoint } from "./LocalSkinCoordinates";
import type { PatternMark, PatternRecipeName } from "./PatternRecipes";

/**
 * Which generated decal sheet (see scripts/mascot/build_visual_atlas.py)
 * stands in for a procedural pattern recipe once its atlas has loaded.
 * "soft-stripes" has no generated equivalent — it stays fully procedural.
 * "circuit-garden-decals" was generated but isn't wired to a recipe yet
 * (see docs/mascot/GENERATED_ASSET_MANIFEST.md) — available for a future preset.
 */
const RECIPE_TO_GENERATED_SHEET: Partial<Record<PatternRecipeName, string>> = {
  // Soft Signal Plush default — sparse fabric patches, not dense bubble terrazzo.
  "terrazzo-confetti": "soft-plush-decals",
  "constellation-freckles": "constellation-decals",
};

/**
 * Resolves and draws the stable local-space print marks generated by
 * `PatternRecipes.generatePatternMarks`. Resolution reuses the shared
 * bone-blending technique (`LocalSkinCoordinates.resolveLocalPoint`), so
 * every mark stays attached to the body during turns/stretch/tumble —
 * upgrade spec Problem 2.
 */

export interface ResolvedPatternMark {
  x: number;
  y: number;
  rotation: number;
  radiusAlong: number;
  radiusAcross: number;
  color: string;
  shape: PatternMark["shape"];
}

/** Reference px-per-segment used to turn a mark's local "along" size into pixels — matches DEFAULT_CREATURE_RECIPE.spine.segmentLength. */
const SEGMENT_LENGTH_REFERENCE_PX = 12;

export function resolvePatternMark(
  mark: PatternMark,
  ribs: readonly RibPoint[],
  widths: readonly number[] | undefined,
  palette: AppearancePalette,
  patternScale: number,
): ResolvedPatternMark | null {
  const resolved = resolveLocalPoint({ u: mark.u, v: mark.v }, ribs, {
    widths,
  });
  if (!resolved) return null;

  const scale = clamp(patternScale, 0.4, 2.2);
  const color =
    mark.colorRole === "primary"
      ? palette.printPrimary
      : mark.colorRole === "secondary"
        ? palette.printSecondary
        : palette.highlight;

  return {
    x: resolved.x,
    y: resolved.y,
    rotation: mark.rotation + Math.atan2(resolved.normalY, resolved.normalX),
    radiusAlong: mark.along * SEGMENT_LENGTH_REFERENCE_PX * scale,
    radiusAcross: mark.across * resolved.width * scale,
    color,
    shape: mark.shape,
  };
}

/**
 * Draws every mark clipped to the caller's already-active clip region (the
 * body silhouette). When `atlas` is ready and `recipe` maps to a generated
 * decal sheet (see `RECIPE_TO_GENERATED_SHEET`), each mark deterministically
 * picks one of that sheet's sprites (via the mark's own stable `seed`, so
 * the choice never flickers frame to frame) and draws it in place of the
 * procedural ellipse — same resolved position/rotation/scale either way,
 * so nothing needs to change about how marks stay attached to the body.
 * Falls back to the procedural shape whenever the atlas isn't ready yet,
 * failed to load, or the recipe has no generated sheet.
 */
export function drawProceduralPrint(
  ctx: CanvasRenderingContext2D,
  marks: readonly PatternMark[],
  ribs: readonly RibPoint[],
  widths: readonly number[] | undefined,
  palette: AppearancePalette,
  tuning: AppearanceTuningOverrides,
  atlas?: GeneratedDecalAtlas | null,
  recipe?: PatternRecipeName,
): void {
  if (marks.length === 0) return;
  const contrast = clamp(tuning.patternContrast, 0, 1);
  const baseAlpha = 0.3 + contrast * 0.5;

  const sheetName = recipe ? RECIPE_TO_GENERATED_SHEET[recipe] : undefined;
  const atlasReady = Boolean(atlas && sheetName && atlas.isReady());
  const image = atlasReady ? (atlas as GeneratedDecalAtlas).getImage() : null;
  const sprites =
    atlasReady && sheetName
      ? (atlas as GeneratedDecalAtlas).getSpritesForSheet(sheetName)
      : [];

  for (const mark of marks) {
    const resolved = resolvePatternMark(
      mark,
      ribs,
      widths,
      palette,
      tuning.patternScale,
    );
    if (!resolved) continue;
    if (resolved.radiusAlong <= 0 || resolved.radiusAcross <= 0) continue;

    ctx.save();
    ctx.translate(resolved.x, resolved.y);
    ctx.rotate(resolved.rotation);
    ctx.globalAlpha = resolved.shape === "line" ? baseAlpha * 0.85 : baseAlpha;

    if (image && sprites.length > 0) {
      const spriteIndex =
        Math.floor((mark.seed / 1000) * sprites.length) % sprites.length;
      const sprite = sprites[spriteIndex];
      const size = Math.max(1, resolved.radiusAlong * 2);
      const aspect = sprite.height / Math.max(1, sprite.width);
      const drawWidth = size;
      const drawHeight = size * aspect;
      ctx.drawImage(
        image,
        sprite.x,
        sprite.y,
        sprite.width,
        sprite.height,
        -drawWidth / 2,
        -drawHeight / 2,
        drawWidth,
        drawHeight,
      );
    } else {
      ctx.fillStyle = resolved.color;
      ctx.beginPath();
      ctx.ellipse(
        0,
        0,
        Math.max(0.4, resolved.radiusAlong),
        Math.max(0.4, resolved.radiusAcross),
        0,
        0,
        Math.PI * 2,
      );
      ctx.fill();
    }
    ctx.restore();
  }

  ctx.globalAlpha = 1;
}
