import { PLAYER_TUNING, getPlayerYBounds } from "./config";
import type {
  EnemySkin,
  GameDifficulty,
  GameModel,
  Player,
  ShipSkin,
} from "./types";

export function createPlayer(width: number, height: number): Player {
  const spawnY = getPlayerYBounds(width, height).respawnY;
  return {
    bankTilt: 0,
    drones: [],
    fireCooldown: 0,
    hull: PLAYER_TUNING.hullMax,
    hullMax: PLAYER_TUNING.hullMax,
    invincibleTimer: PLAYER_TUNING.respawnInvincible,
    lives: 3,
    magnetTimer: 0,
    powerInvincibleTimer: 0,
    r: PLAYER_TUNING.r,
    respawnTimer: 0,
    shieldHp: 0,
    shieldMax: PLAYER_TUNING.shieldMax,
    shotParity: 0,
    super: 0,
    superActiveTimer: 0,
    vx: 0,
    vy: 0,
    weapon: "pulse",
    weaponLevel: 1,
    x: width / 2,
    y: spawnY,
  };
}

export function createModel(
  width: number,
  height: number,
  best: number,
  difficulty: GameDifficulty = "easy",
  shipSkin: ShipSkin = "circuit",
  enemySkin: EnemySkin = "topdown",
): GameModel {
  return {
    activeModifiers: [],
    banner: {
      kind: "sector",
      subtitle: "Basic drills for basic birds",
      timer: 0,
      title: "Sector 1: Training Coop",
    },
    best,
    bullets: [],
    combo: 0,
    comboPulseId: 0,
    comboTimer: 0,
    dpr: 1,
    difficulty,
    dropsSincePowerup: 0,
    dropsSinceWeapon: 0,
    elapsed: 0,
    enemySkin,
    enemies: [],
    floats: [],
    hazards: [],
    height,
    hitStop: 0,
    noDamageStreakWaves: 0,
    particles: [],
    player: createPlayer(width, height),
    pointer: { active: false, x: width / 2, y: getPlayerYBounds(width, height).respawnY },
    powerUps: [],
    score: 0,
    screenFlash: null,
    sector: 1,
    shipSkin,
    sfxQueue: [],
    shake: 0,
    shockwaves: [],
    status: "ready",
    timewarpTimer: 0,
    wave: 0,
    waveClearedNoDamage: true,
    waveCooldown: 0.6,
    weaponPickups: [],
    width,
  };
}
