import { createCharacterSpec } from "../createCharacterSpec";

const TENTACLE_ANGLES = [0.26, 0.35, 0.44, 0.56, 0.65, 0.74] as const;

/** Luma: a pulsing area-preserved bell with six trailing arms. */
export const jellyPreset = createCharacterSpec({
  id: "luma-jelly",
  name: "Luma",
  seed: 0x1a6a,
  scale: 1,
  appendages: 6,
  body: {
    shape: "soft-polygon",
    orientationMode: "upright",
    maxLean: 0.22,
    radius: 48,
    squashAmount: 0.24,
    segmentCount: 1,
    segmentSpacing: 11,
    stiffness: 0.6,
    maxJointAngleDifference: Math.PI / 2,
    widthProfile: { kind: "head-heavy", exponent: 1.5 },
    softBody: {
      boundary: [
        { x: 0, y: -1.04 },
        { x: 0.48, y: -0.9 },
        { x: 0.82, y: -0.56 },
        { x: 0.96, y: -0.08 },
        { x: 0.82, y: 0.38 },
        { x: 0.54, y: 0.27 },
        { x: 0.27, y: 0.43 },
        { x: 0, y: 0.29 },
        { x: -0.27, y: 0.43 },
        { x: -0.54, y: 0.27 },
        { x: -0.82, y: 0.38 },
        { x: -0.96, y: -0.08 },
        { x: -0.82, y: -0.56 },
        { x: -0.48, y: -0.9 },
      ],
      deformationMode: "pulse",
      damping: 0.925,
      guideStrength: 0.22,
      edgeStiffness: 0.7,
      bendStiffness: 0.28,
      shapeStiffness: 0.15,
      areaStiffness: 0.58,
      centerStiffness: 0.52,
      constraintIterations: 8,
      deformationFrequency: 0.92,
      deformationAmount: 0.17,
    },
  },
  dynamics: {
    frequency: 1.45,
    damping: 0.62,
    response: 0.12,
    maxSpeed: 270,
    maxAcceleration: 3000,
    facingResponsiveness: 6.8,
    movementFrequency: 0.95,
  },
  idle: {
    delay: 1.8,
    breathingFrequency: 0.8,
    breathingAmount: 0.026,
    lookAroundAmount: 0.52,
    wanderRadius: 150,
  },
  appendageDefaults: {
    mode: "trailing",
    segmentLengths: [18, 17, 16, 15, 14, 13],
    maxReach: 93,
    restingFootRadius: 84,
    anchor: { radius: 0.68 },
    step: {
      threshold: 20,
      duration: 0.3,
      height: 6,
      predictionTime: 0.05,
      cooldown: 0.1,
      variation: 2,
    },
    spring: {
      damping: 0.948,
      guideStrength: 0.1,
      gravity: 88,
      curl: 720,
      constraintIterations: 6,
    },
    stiffness: 0.42,
    drag: 0.36,
    thickness: 7,
  },
  appendageFactory: (base, index) => {
    const angle = TENTACLE_ANGLES[index] * Math.PI;
    const centerDistance = Math.abs(index - 2.5) / 2.5;
    return {
      ...base,
      id: `luma-tentacle-${index + 1}`,
      anchor: { ...base.anchor, angle },
      preferredFoot: {
        ...base.preferredFoot,
        angle,
        radius: 82 + centerDistance * 8,
      },
      spring: {
        ...base.spring,
        damping: 0.945 + centerDistance * 0.008,
        curl: 620 + centerDistance * 260,
      },
      thickness: 7.8 - centerDistance * 2.8,
      gaitPhase: index / 6,
      gaitGroup: index % 3,
      preferredBendDirection: index < 3 ? 1 : -1,
    };
  },
  gait: {
    style: "free",
    phaseOffsets: [0, 0.16, 0.33, 0.5, 0.66, 0.83],
    cadence: 0.9,
    phaseWindow: 1,
    maxConcurrentSteps: 0,
    maxConcurrentStepsRunning: 0,
    maxConcurrentPerGroup: 0,
    minPlantedFeet: 0,
    runningSpeed: 1,
    emergencyStretchRatio: 2,
  },
  eyes: {
    count: 2,
    spacing: 14,
    offsetX: 0,
    offsetY: -12,
    spacingAngle: 0,
    mouthOffsetX: 0,
    mouthOffsetY: 1,
    size: 6.8,
    pupilSize: 2.7,
    pupilTrackingStrength: 0.7,
    velocityAnticipation: 0.1,
    blink: { minimumInterval: 2.5, maximumInterval: 6.4, duration: 0.17 },
  },
  personality: {
    curiosity: 0.95,
    confidence: 0.36,
    energy: 0.5,
    elasticity: 0.96,
    anticipation: 0.62,
    overshoot: 0.88,
    appendageStiffness: 0.3,
    glowResponsiveness: 0.9,
  },
  rendering: {
    bodyColor: "rgba(185, 151, 245, 0.9)",
    bodyHighlightColor: "rgba(255, 244, 255, 0.52)",
    bodyShadowColor: "rgba(29, 13, 52, 0.3)",
    appendageColor: "rgba(167, 127, 232, 0.84)",
    eyeColor: "#fcf9ff",
    pupilColor: "#27163c",
    outlineColor: "rgba(242, 222, 255, 0.5)",
    outlineWidth: 1.1,
    glowColor: "#c084fc",
    glow: 0.72,
    appendageThickness: 7,
    debugPalette: ["#c4b5fd", "#67e8f9", "#f9a8d4", "#fde68a"],
  },
  performance: {
    fixedTimeStep: 1 / 120,
    maxFrameDelta: 0.05,
    maxSimulationSteps: 6,
    solverIterations: 7,
    lowPowerSolverIterations: 4,
    dprCap: 2,
  },
});
