import { createCharacterSpec } from "../createCharacterSpec";

const TAIL_ANGLES = [Math.PI - 0.13, Math.PI, Math.PI + 0.13] as const;

/** Tinker: an area-preserved soft manta with three trailing chains. */
export const mantaPreset = createCharacterSpec({
  id: "tinker-manta",
  name: "Tinker",
  seed: 0x71a7,
  scale: 1,
  appendages: 3,
  body: {
    shape: "soft-polygon",
    orientationMode: "velocity",
    maxLean: 0.4,
    radius: 58,
    squashAmount: 0.16,
    segmentCount: 1,
    segmentSpacing: 12,
    stiffness: 0.68,
    maxJointAngleDifference: Math.PI / 2,
    widthProfile: { kind: "elliptical" },
    softBody: {
      boundary: [
        { x: 1.02, y: 0 },
        { x: 0.58, y: 0.23 },
        { x: 0.16, y: 0.55 },
        { x: -0.08, y: 1 },
        { x: -0.32, y: 0.58 },
        { x: -0.62, y: 0.24 },
        { x: -0.76, y: 0.08 },
        { x: -0.8, y: 0 },
        { x: -0.76, y: -0.08 },
        { x: -0.62, y: -0.24 },
        { x: -0.32, y: -0.58 },
        { x: -0.08, y: -1 },
        { x: 0.16, y: -0.55 },
        { x: 0.58, y: -0.23 },
      ],
      deformationMode: "wing",
      damping: 0.91,
      guideStrength: 0.24,
      edgeStiffness: 0.76,
      bendStiffness: 0.32,
      shapeStiffness: 0.14,
      areaStiffness: 0.64,
      centerStiffness: 0.58,
      constraintIterations: 8,
      deformationFrequency: 1.35,
      deformationAmount: 0.24,
    },
  },
  dynamics: {
    frequency: 1.72,
    damping: 0.57,
    response: 0.14,
    maxSpeed: 420,
    maxAcceleration: 4400,
    facingResponsiveness: 7.2,
    movementFrequency: 1.35,
  },
  idle: {
    delay: 2.2,
    breathingFrequency: 0.72,
    breathingAmount: 0.018,
    lookAroundAmount: 0.45,
    wanderRadius: 210,
  },
  appendageDefaults: {
    mode: "trailing",
    segmentLengths: [24, 23, 22, 20, 18, 16],
    maxReach: 123,
    restingFootRadius: 118,
    anchor: { radius: 0.72 },
    step: {
      threshold: 24,
      duration: 0.28,
      height: 8,
      predictionTime: 0.08,
      cooldown: 0.08,
      variation: 1.5,
    },
    spring: {
      damping: 0.95,
      guideStrength: 0.12,
      gravity: 28,
      curl: 680,
      constraintIterations: 6,
    },
    stiffness: 0.5,
    drag: 0.42,
    thickness: 5.5,
  },
  appendageFactory: (base, index) => {
    const centerTail = index === 1;
    const angle = TAIL_ANGLES[index];
    return {
      ...base,
      id: centerTail ? "tinker-main-tail" : `tinker-ribbon-${index + 1}`,
      anchor: { ...base.anchor, angle, radius: centerTail ? 0.76 : 0.66 },
      preferredFoot: {
        ...base.preferredFoot,
        angle,
        radius: centerTail ? 125 : 108,
      },
      spring: {
        ...base.spring,
        damping: centerTail ? 0.956 : 0.946,
        guideStrength: centerTail ? 0.1 : 0.14,
        curl: centerTail ? 540 : 760,
      },
      thickness: centerTail ? 6.2 : 4.4,
      gaitPhase: index / 3,
      gaitGroup: index,
      preferredBendDirection: index === 0 ? 1 : -1,
    };
  },
  gait: {
    style: "free",
    phaseOffsets: [0, 0.33, 0.66],
    cadence: 1,
    phaseWindow: 1,
    maxConcurrentSteps: 0,
    maxConcurrentStepsRunning: 0,
    maxConcurrentPerGroup: 0,
    minPlantedFeet: 0,
    runningSpeed: 1,
    emergencyStretchRatio: 2,
  },
  eyes: {
    count: 2,
    spacing: 13,
    offsetX: 19,
    offsetY: 0,
    spacingAngle: Math.PI / 2,
    mouthOffsetX: 30,
    mouthOffsetY: 0,
    size: 6.2,
    pupilSize: 2.5,
    pupilTrackingStrength: 0.62,
    velocityAnticipation: 0.18,
    blink: { minimumInterval: 2.9, maximumInterval: 7.1, duration: 0.16 },
  },
  personality: {
    curiosity: 0.92,
    confidence: 0.54,
    energy: 0.7,
    elasticity: 0.78,
    anticipation: 0.84,
    overshoot: 0.82,
    appendageStiffness: 0.38,
    glowResponsiveness: 0.72,
  },
  rendering: {
    bodyColor: "#79d4df",
    bodyHighlightColor: "rgba(235, 255, 255, 0.48)",
    bodyShadowColor: "rgba(3, 20, 35, 0.34)",
    appendageColor: "#62bdcd",
    eyeColor: "#f5fdff",
    pupilColor: "#102b3b",
    outlineColor: "rgba(211, 251, 255, 0.52)",
    outlineWidth: 1.2,
    glowColor: "#46d8ea",
    glow: 0.58,
    appendageThickness: 5.5,
    debugPalette: ["#67e8f9", "#f0abfc", "#fde68a", "#86efac"],
  },
  performance: {
    fixedTimeStep: 1 / 120,
    maxFrameDelta: 0.05,
    maxSimulationSteps: 6,
    solverIterations: 7,
    lowPowerSolverIterations: 4,
    dprCap: 2,
  },
});
