import { createCharacterSpec } from "../createCharacterSpec";

/** Pebble: a buoyant spotted puffer with tiny steering fins. */
export const pufferPreset = createCharacterSpec({
  id: "pebble-puffer",
  name: "Pebble Puffer",
  seed: 0xb0ff,
  appendages: 5,
  body: {
    shape: "soft-polygon",
    orientationMode: "velocity",
    radius: 43,
    squashAmount: 0.3,
    softBody: {
      boundary: [
        { x: 1.02, y: 0 },
        { x: 0.8, y: 0.58 },
        { x: 0.32, y: 0.94 },
        { x: -0.26, y: 0.92 },
        { x: -0.78, y: 0.56 },
        { x: -0.98, y: 0 },
        { x: -0.78, y: -0.56 },
        { x: -0.26, y: -0.92 },
        { x: 0.32, y: -0.94 },
        { x: 0.8, y: -0.58 },
      ],
      deformationMode: "pulse",
      damping: 0.91,
      guideStrength: 0.26,
      edgeStiffness: 0.74,
      bendStiffness: 0.3,
      shapeStiffness: 0.13,
      areaStiffness: 0.72,
      centerStiffness: 0.62,
      constraintIterations: 8,
      deformationFrequency: 0.66,
      deformationAmount: 0.09,
    },
  },
  dynamics: {
    frequency: 1.08,
    damping: 0.9,
    response: 0.04,
    maxSpeed: 250,
    maxAcceleration: 2200,
    facingResponsiveness: 6,
  },
  appendageDefaults: {
    mode: "trailing",
    segmentLengths: [11, 10, 8],
    maxReach: 27,
    restingFootRadius: 25,
    anchor: { radius: 0.78 },
    spring: {
      damping: 0.94,
      guideStrength: 0.2,
      gravity: 16,
      curl: 440,
      constraintIterations: 5,
    },
    drag: 0.5,
    thickness: 8,
  },
  appendageFactory: (base, index) => {
    const angles = [Math.PI, Math.PI - 0.25, Math.PI + 0.25, -1.45, 1.45];
    const angle = angles[index];
    return {
      ...base,
      id: index === 0 ? "pebble-tail" : `pebble-fin-${index}`,
      anchor: { ...base.anchor, angle },
      preferredFoot: { ...base.preferredFoot, angle, radius: index === 0 ? 31 : 24 },
      thickness: index === 0 ? 9.5 : 6.8,
      gaitGroup: index,
    };
  },
  gait: {
    style: "free",
    maxConcurrentSteps: 0,
    maxConcurrentStepsRunning: 0,
    maxConcurrentPerGroup: 0,
    minPlantedFeet: 0,
  },
  eyes: {
    spacing: 15,
    spacingAngle: Math.PI / 2,
    offsetX: 18,
    offsetY: 0,
    mouthOffsetX: 34,
    mouthOffsetY: 0,
    size: 6.2,
    pupilSize: 2.6,
  },
  personality: {
    curiosity: 0.74,
    confidence: 0.32,
    energy: 0.38,
    elasticity: 1,
    anticipation: 0.48,
    overshoot: 0.72,
  },
  rendering: {
    bodyColor: "#d7b86c",
    bodyHighlightColor: "rgba(255, 245, 194, 0.5)",
    bodyShadowColor: "rgba(58, 39, 16, 0.28)",
    appendageColor: "#caa85f",
    eyeColor: "#fffdf4",
    pupilColor: "#2d2619",
    outlineColor: "rgba(255, 241, 192, 0.62)",
    outlineWidth: 1.2,
    glowColor: "#e8c978",
    glow: 0.24,
    markingStyle: "spots",
    markingColor: "rgba(79, 66, 42, 0.58)",
  },
});
